language: php

php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'

install:
    - composer install

script:
    - vendor/bin/phpunit

after_success:
    - bash <(curl -s https://codecov.io/bash) -f build/logs/clover.xml
    - vendor/bin/test-reporter
